env: order-dev2.yml
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///pm111?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: order

server:
  port: 8082
PRODUCT:
  ribbon:
     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
