env: prodcut-dev
spring:
  application:
    name: product
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///pm111?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

rabbitmq:
  host: 192.168.1.10
  username: guest
  password: guest
  port: 5672

server:
  port: 8083
